# Generated by Django 4.1 on 2022-09-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_curso_camada_alter_estudiantes_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
    ]
